### ISSUE TITLE
create single pages

### ISSUE THREAD

**Issue by codebhendi** [SaptakS/DjangoTut-WebClient#37]

**Comment by vivekanand1101** [comment]
![13709545_586254818221631_628173112_o](https://cloud.githubusercontent.com/assets/9296805/20453272/3c9eb51c-ae44-11e6-889e-c4b40805a138.jpg)

**Comment by vivekanand1101** [comment]
haha lol this is bhendi
![13709545_586254818221631_628173112_o](https://cloud.githubusercontent.com/assets/9296805/20453290/b1ae1898-ae44-11e6-8e0c-5db53c700d52.jpg)

**Comment by vivekanand1101** [comment]
![batman](https://cloud.githubusercontent.com/assets/9296805/20457693/8ebe74b4-aeb6-11e6-8232-f508e7e84aa9.jpg)

**Comment by vivekanand1101** [comment]
![batman](https://cloud.githubusercontent.com/assets/9296805/20457848/9c15dc52-aeba-11e6-8b4b-c1bae80d47f4.jpg)
![batman](https://cloud.githubusercontent.com/assets/9296805/20457850/a0551fb2-aeba-11e6-916d-72ac54e4eedc.jpg)

haha lol 
![batman](https://cloud.githubusercontent.com/assets/9296805/20457718/0c8805b8-aeb7-11e6-998a-fbea02296679.jpg)

**Comment by codebhendi** [comment]
![watman](https://cloud.githubusercontent.com/assets/7371972/20656755/eb8b441a-b555-11e6-9c63-8462168739fd.jpg)

**Comment by vivekanand1101** [comment]
[Network_Security.pdf](https://github.com/SaptakS/DjangoTut-WebClient/files/819388/Network_Security.pdf)
